### ISSUE TITLE
Always deploys placeholder HTML file

### ISSUE THREAD

**Issue by danpalmer** [danakim/gh-action-deploy-netlify#1]
I may be using this wrong, but despite following the documentation and building a `build` directory with a site in it, the placeholder HTML file in this repo always gets deployed and my site doesn't.

**Comment by danakim** [comment]
Hey @danpalmer - looking into it!

**Comment by danakim** [comment]
Hi @danpalmer - the issue has been solved, I have updated the README to reflect the new, fixed steps. More specifically:

* the `uses` step has a new link from where to pull the action (L46 `uses: danakim/gh-action-deploy-netlify@master`)
* the `Build the website` step now specifies a different directory where to output the site files, a directory which you will also have to create initially, before building
